# Generated by Django 6.1.1 on 2026-09-24 06:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_user_alter_conversationmember_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFriend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('friend', models.ForeignKey(db_column='friend_id', on_delete=django.db.models.deletion.CASCADE, related_name='friend_links_received', to='chat.user')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='friend_links', to='chat.user')),
            ],
            options={
                'db_table': 'user_friends',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(related_name='friend_of', through='chat.UserFriend', to='chat.user'),
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('invitation_id', models.UUIDField(db_column='id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPT', 'Accepted'), ('REJECT', 'Rejected')], db_column='status', default='PENDING', max_length=10)),
                ('send_time', models.DateTimeField(auto_now_add=True, db_column='send_time')),
                ('sender', models.ForeignKey(db_column='sender_id', on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to='chat.user')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='received_invitations', to='chat.user')),
            ],
            options={
                'db_table': 'invitation',
                'indexes': [models.Index(fields=['user', 'status'], name='idx_invitation_user_status')],
            },
        ),
        migrations.AddIndex(
            model_name='userfriend',
            index=models.Index(fields=['user'], name='idx_user_friend_user'),
        ),
        migrations.AddIndex(
            model_name='userfriend',
            index=models.Index(fields=['friend'], name='idx_user_friend_friend'),
        ),
        migrations.AddConstraint(
            model_name='userfriend',
            constraint=models.UniqueConstraint(fields=('user', 'friend'), name='uq_user_friend'),
        ),
        migrations.AddConstraint(
            model_name='userfriend',
            constraint=models.CheckConstraint(condition=models.Q(('user', models.F('friend')), _negated=True), name='ck_user_friend_not_self'),
        ),
    ]
