# Generated by Django 6.1.1 on 2026-09-26 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_message_reply_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.FileField(blank=True, db_column='avatar', null=True, upload_to='avatars/'),
        ),
    ]
