# Generated by Django 6.1.1 on 2026-09-26 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, db_column='bio'),
        ),
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.CharField(blank=True, choices=[('female', 'Female'), ('male', 'Male')], db_column='sex', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='short_bio',
            field=models.CharField(blank=True, db_column='short_bio', max_length=160),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], db_column='status', default='offline', max_length=10),
        ),
    ]
