# Generated by Django 6.1.1 on 2026-10-07 05:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_conversation_last_seq'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomInvitation',
            fields=[
                ('invitation_id', models.UUIDField(db_column='id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPT', 'Accepted'), ('REJECT', 'Rejected')], db_column='status', default='PENDING', max_length=10)),
                ('send_time', models.DateTimeField(auto_now_add=True, db_column='send_time')),
                ('conversation', models.ForeignKey(db_column='conversation_id', on_delete=django.db.models.deletion.CASCADE, related_name='room_invitations', to='chat.conversation')),
                ('sender', models.ForeignKey(db_column='sender_id', on_delete=django.db.models.deletion.CASCADE, related_name='sent_room_invitations', to='chat.user')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='received_room_invitations', to='chat.user')),
            ],
            options={
                'db_table': 'room_invitations',
                'indexes': [models.Index(fields=['user', 'status', 'send_time'], name='idx_room_inv_user_status_time'), models.Index(fields=['sender', 'status'], name='idx_room_inv_sender_status')],
            },
        ),
    ]
